<a 
href="https://colab.research.google.com/github/adilo231/Python-for-machine-learning/blob/main/Chap%20-2-%20Modules%20scientifiques/1.2 - Numpy : Indexing%2C Slicing%2C Boolean Indexing.ipynb" 
target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy :

NumPy est le package fondamental pour le calcul scientifique en Python. Il s'agit d'une bibliothèque Python qui fournit un objet tableau multidimensionnel, divers objets dérivés (tels que des tableaux masqués et des matrices) et un assortiment de routines pour des opérations rapides sur des tableaux, y compris mathématiques, logiques, manipulation de forme, tri, sélection, E/S , transformées de Fourier discrètes, algèbre linéaire de base, opérations statistiques de base, simulation aléatoire et bien plus encore.

Pour accéder à NumPy et à ses fonctions, importez-le dans votre code Python comme ceci :



In [1]:
import numpy as np

Nous raccourcissons le nom importé en np pour une meilleure lisibilité du code à l'aide de NumPy. Il s'agit d'une convention largement adoptée que vous devez suivre afin que toute personne travaillant avec votre code puisse facilement la comprendre.

## Générateurs de tableaux **ndarray**


In [2]:
A = np.array([1, 2, 3]) # générateur par défaut, qui permet de convertir des listes (ou autres objets) en tableau ndarray
A = np.zeros((2, 3)) # tableau de 0 aux dimensions 2x3
B = np.ones((2, 3)) # tableau de 1 aux dimensions 2x3


In [3]:
np.random.seed(0)
C = np.random.randn(2, 3) # tableau aléatoire (distribution normale) aux dimensions 2x3
D = np.random.rand(2, 3) # tableau aléatoire (distribution uniforme)

In [4]:
size = (2, 3)
E = np.random.randint(0, 10, size) # tableau d'entiers aléatoires de 0 a 10 et de dimension 2x3
print(E)

[[8 1 5]
 [9 8 9]]


In [5]:
B = np.eye(4, dtype=bool) # créer une matrice identité et convertit les éléments en type bool.
print(B)

[[ True False False False]
 [False  True False False]
 [False False  True False]
 [False False False  True]]


In [6]:
A = np.linspace(0,10, 11) # np.linspace(start,end, number of elements)
B = np.arange(0, 10, 1) # np.linspace(start,end, step)
print(A)
print(B)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[0 1 2 3 4 5 6 7 8 9]


In [7]:
A = np.linspace(5, 10,7, dtype=np.float16) # définit le type et la place a occuper sur la mémoire
print("float16: ",A)
A = np.linspace(5,10,7, dtype=np.float32)
print("float32: ",A)
A = np.linspace(5,10,7, dtype=np.float64)
print("float64: ",A)

float16:  [ 5.     5.832  6.668  7.5    8.336  9.164 10.   ]
float32:  [ 5.         5.8333335  6.6666665  7.5        8.333333   9.166667
 10.       ]
float64:  [ 5.          5.83333333  6.66666667  7.5         8.33333333  9.16666667
 10.        ]


## Attributs importants

In [8]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
 
print(A.size) # le nombre d'éléments dans le tableau A
print(A.shape) # les dimensions du tableau A (sous forme de Tuple)
print(type(A.shape)) # voici la preuve que la shape est un tuple
print(A.shape[0]) # le nombre d'éléments dans la premiere dimension de A

6
(2, 3)
<class 'tuple'>
2


## Méthodes importantes
- **reshape()** : pour redimensionner un tableau
- **ravel()** : pour applatir un tableau (qu'il ne fasse plus qu'une dimension)
- **squeeze()** : quand une dimension est égale a 1, cette dimension disparait
- **concatenate()** : assemble 2 tableaux ensemble selon un axes (existe aussi en hstack et vstack)

In [9]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
 
A = A.reshape((3, 2)) # redimensionne le tableau A (3 lignes, 2 colonnes)
print("reshape: ",A)
B = A.ravel() # Aplatit le tableau A (une seule dimension)
print("ravel: ",B)

reshape:  [[0. 0.]
 [0. 0.]
 [0. 0.]]
ravel:  [0. 0. 0. 0. 0. 0.]


In [10]:
A= np.array([1,2,5,3])
print(A)
print(A.shape)

A= A.reshape((A.shape[0],1))
print(A.shape)

A=A.squeeze()
print(A.shape)

[1 2 5 3]
(4,)
(4, 1)
(4,)


In [11]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
B = np.ones((2, 3)) # création d'un tableau de shape (2, 3)

np.concatenate((A, B), axis=0) # axe 0 : équivalent de np.vstack((A, B))

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.concatenate((A, B), axis=1) # axe 1 : équivalent de np.hstack((A, B))

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [13]:
A = np.zeros((2, 3)) # création d'un tableau de shape (2, 3)
B = np.ones((2, 3)) # création d'un tableau de shape (2, 3)
C = np.hstack((A,B))
print(C)
print(C.shape)



[[0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]
(2, 6)


In [14]:
C = np.vstack((A,B))
print(C)
print(C.shape)

[[0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
(4, 3)


## Exercice

In [15]:
def initialisation(m, n):
    # m : nombre de lignes
    # n : nombre de colonnes
    # retourne une matrice aléatoire (m, n+1)
    # avec une colonne biais (remplie de "1") tout a droite
    return X   


In [16]:

def initialisation(m, n):
    # m : nombre de lignes
    # n : nombre de colonnes
    # retourne une matrice aléatoire (m, n+1)
    # avec une colonne biais (remplie de "1") tout a droite
    
    #--------> votre code ici <--------------#
    return X   
initialisation(3, 3)