<a href="https://colab.research.google.com/github/MachineLearnia/Python-Machine-Learning/blob/master/12%20-%20Numpy%20Maths%20et%20Statistiques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy : Mathématiques

In [2]:
import numpy as np

## Méthodes de bases (les plus utiles) de la classe ndarray

In [34]:
A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print("la somme des elements",A.sum()) # effectue la somme de tous les éléments du tableau
print("la somme des elements colone",A.sum(axis=0)) # effectue la somme des colonnes (somme sur éléments des les lignes)
print("la somme des elements ligne",A.sum(axis=1)) # effectue la somme des lignes (somme sur les éléments des colonnes)
print("la somme cumulative",A.cumsum(axis=0)) # effectue la somme cumulée
 
print(A.prod()) # effectue le produit
print(A.cumprod()) # effectue le produit cumulé
 
print(A.min()) # trouve le minimum du tableau
print(A.max()) # trouve le maximum du tableau
 
print(A.mean()) # calcule la moyenne
print(A.std()) # calcule l'ecart type,
print(A.var()) # calcule la variance

[[1 2 3]
 [4 5 6]]
la somme des elements 21
la somme des elements colone [5 7 9]
la somme des elements ligne [ 6 15]
la somme cumulative [[1 2 3]
 [5 7 9]]
720
[  1   2   6  24 120 720]
1
6
3.5
1.707825127659933
2.9166666666666665


Une méthode tres importante : la méthode **argsort()**

In [19]:
A = np.random.randint(0, 10, [5, 5]) # tableau aléatoire
print(A)

[[4 2 6 2 4]
 [7 7 4 0 1]
 [6 6 6 3 3]
 [2 0 7 7 3]
 [5 7 4 9 7]]


In [20]:
print(A.argsort()) # retourne les index pour trier chaque ligne du tableau 

[[1 3 0 4 2]
 [3 4 2 0 1]
 [3 4 0 1 2]
 [1 0 4 2 3]
 [2 0 1 4 3]]


In [21]:
print(A[:,0].argsort()) # retourne les index pour trier la colonne 0 de A

[3 0 4 2 1]


In [22]:
A = A[A[:,0].argsort(), :] # trie les colonnes du tableau selon la colonne 0.
A

array([[2, 0, 7, 7, 3],
       [4, 2, 6, 2, 4],
       [5, 7, 4, 9, 7],
       [6, 6, 6, 3, 3],
       [7, 7, 4, 0, 1]])

## Numpy Statistics
Correlation de Pearson :

In [23]:
B = np.random.randn(3, 3) # nombres aléatoires 3x3
 
# retourne la matrice de corrélation de B
print(np.corrcoef(B))

[[ 1.         -0.63427277  0.99937797]
 [-0.63427277  1.         -0.66114251]
 [ 0.99937797 -0.66114251  1.        ]]


In [24]:
# retourne la matrice de corrélation entre les lignes 0 et 1 de B
print(np.corrcoef(B[:,0], B[:, 1]))

[[1.         0.81847981]
 [0.81847981 1.        ]]


np.unique() :

In [15]:
np.random.seed(0)
A = np.random.randint(0, 5, [5,5])
A

array([[4, 0, 3, 3, 3],
       [1, 3, 2, 4, 0],
       [0, 4, 2, 1, 0],
       [1, 1, 0, 1, 4],
       [3, 0, 3, 0, 2]])

In [16]:
np.unique(A)

array([0, 1, 2, 3, 4])

In [17]:
values, counts = np.unique(A, return_counts=True)

for i, j in zip(values[counts.argsort()], counts[counts.argsort()]):
    print(f'valeur {i} apparait {j}')

valeur 2 apparait 3
valeur 4 apparait 4
valeur 1 apparait 5
valeur 3 apparait 6
valeur 0 apparait 7


Calculs statistiques en présence de données manquates (NaN)

In [36]:
A = np.random.randn(5, 5)
A[0, 2] = np.nan # insere un NaN dans la matrice A
 
print('ratio NaN/zise:', (np.isnan(A).sum()/A.size)) # calcule la proportion de NaN dans A
 
print('moyenne sans NaN:', np.nanmean(A)) # calcule la moyenne de A en ignorant les NaN

ratio NaN/zise: 0.04
moyenne sans NaN: 0.1832816316588837


## Algebre Linéaire

In [38]:
A = np.ones((2,3))
B = np.ones((3,3))

print(A.T) # transposé de la matrice A (c'est un attribut de ndarray)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [39]:
print(A.dot(B)) # produit matriciel A.B

[[3. 3. 3.]
 [3. 3. 3.]]


In [45]:
A = np.random.randint(0, 10, [3, 3])
 
print('det=', np.linalg.det(A)) # calcule le determinant de A
print('inv A:\n', np.linalg.inv(A)) # calcul l'inverse de A

det= 61.00000000000001
inv A:
 [[ 0.08196721  0.63934426 -0.60655738]
 [-0.13114754 -0.62295082  0.7704918 ]
 [ 0.21311475  0.26229508 -0.37704918]]


In [44]:
val, vec = np.linalg.eig(A)
print('valeur propre:\n', val) # valeur propre
print('vecteur propre:\n', vec) # vecteur propre

valeur propre:
 [ 8.91371956 -0.86320273  1.94948316]
vecteur propre:
 [[-0.27183844 -0.6838339   0.39494311]
 [-0.4097407  -0.15279739 -0.73291062]
 [-0.87075623  0.71345929  0.55395123]]


## Fonctions mathématiques

In [13]:
A = np.linspace(1,10,10)
print(np.exp(A)) # calclule l'exponontielle pour tous les element d'un tableau
print(np.log(A)) # calclule le logaritheme pour tous les element d'un tableau
print(np.cos(A)) # calclule le cosinus pour tous les element d'un tableau
print(np.sin(A)) # calclule le sinus pour tous les element d'un tableau

[2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]
[ 0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029
  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849 -0.54402111]


## Exercice 

Standardisez la matrice suivante, c'est a dire effectuez le calcul suivant :
$A = \frac{A - mean(A_{colonne})}{std(A_{colonne})}$

In [30]:
np.random.seed(0)
A = np.random.randint(0, 100, [10, 5])
A

array([[44, 47, 64, 67, 67],
       [ 9, 83, 21, 36, 87],
       [70, 88, 88, 12, 58],
       [65, 39, 87, 46, 88],
       [81, 37, 25, 77, 72],
       [ 9, 20, 80, 69, 79],
       [47, 64, 82, 99, 88],
       [49, 29, 19, 19, 14],
       [39, 32, 65,  9, 57],
       [32, 31, 74, 23, 35]])

In [35]:
#solution ici

In [33]:
print(D.mean(axis=0)) # les moyennes sont toutes = 0
print(D.std(axis=0)) # les std sont tous = 1 

[-2.22044605e-17 -4.44089210e-17  0.00000000e+00 -1.22124533e-16
 -4.44089210e-17]
[1. 1. 1. 1. 1.]
