<a 
href="https://colab.research.google.com/github/adilo231/Python-for-machine-learning/blob/main/Chap%20-2-%20Modules%20scientifiques/1.4 - Numpy Broadcasting.ipynb" 
target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy et Broadcasting

In [ ]:
import numpy as np

In [3]:
A = np.ones((2, 3))
B = 3
print(A+B) # résultat 1
 
A = np.ones((2, 3))
B = np.ones((2, 1)) # B a une colonne, elle sera étendu sur les trois colonnes de A
print(A+B) # résultat 2
 
A = np.ones((2, 3))
B = np.ones((2, 2))


[[4. 4. 4.]
 [4. 4. 4.]]
[[2. 2. 2.]
 [2. 2. 2.]]
